// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitBazzar1.AdminPanel.Models
{
    public partial class Customers
    {
        public Customers()
        {
            CartItem = new HashSet<CartItem>();
            Orders = new HashSet<Orders>();
            Purchase = new HashSet<Purchase>();
            Review = new HashSet<Review>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }

        public virtual ICollection<CartItem> CartItem { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}