// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitBazzar1.AdminPanel.Models
{
    public partial class Orders
    {
        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public decimal? TotalAmount { get; set; }
        public int? ProductId { get; set; }

        public virtual Customers Customer { get; set; }
        public virtual Products Product { get; set; }
    }
}