// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FruitBazzar1.Api.Models;

public partial class CartItem
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public DateTime? Date { get; set; }

    public int? CustomersId { get; set; }

    public virtual Customers Customers { get; set; }

    public virtual Products Product { get; set; }
}